export type WardrobeItem = {
  id: string;
  name: string;
  category: "Tops" | "Bottoms" | "Outerwear" | "Shoes" | "Accessories";
  color: string;
  season: ("Spring" | "Summer" | "Autumn" | "Winter")[];
  brand: string;
  occasion: ("Casual" | "Smart Casual" | "Formal" | "Lounge")[];
  material: string;
  isFavorite: boolean;
  wearCount: number;
  lastWorn?: string;
  dateAdded: string;
  imageUrl: string;
  notes?: string;
};

export const MOCK_WARDROBE: WardrobeItem[] = [
  {
    id: "w-1",
    name: "Classic White Linen Shirt",
    category: "Tops",
    color: "White",
    season: ["Spring", "Summer"],
    brand: "Acne Studios",
    occasion: ["Casual", "Smart Casual"],
    material: "Linen",
    isFavorite: true,
    wearCount: 14,
    lastWorn: "2023-09-12",
    dateAdded: "2023-04-01",
    imageUrl: "/images/wardrobe/white-shirt.png",
    notes: "Requires gentle ironing. Great for warm weather layering.",
  },
  {
    id: "w-2",
    name: "Dark Selvedge Denim",
    category: "Bottoms",
    color: "Navy",
    season: ["Spring", "Autumn", "Winter"],
    brand: "A.P.C.",
    occasion: ["Casual", "Smart Casual"],
    material: "Cotton",
    isFavorite: true,
    wearCount: 42,
    lastWorn: "2023-10-05",
    dateAdded: "2022-11-15",
    imageUrl: "/images/wardrobe/jeans.png",
    notes: "Do not wash frequently to maintain raw look.",
  },
  {
    id: "w-3",
    name: "Beige Cashmere Sweater",
    category: "Tops",
    color: "Beige",
    season: ["Autumn", "Winter"],
    brand: "Loro Piana",
    occasion: ["Smart Casual", "Formal"],
    material: "Cashmere",
    isFavorite: false,
    wearCount: 8,
    lastWorn: "2023-02-14",
    dateAdded: "2022-12-05",
    imageUrl: "/images/wardrobe/sweater.png",
    notes: "Dry clean only. Extremely soft.",
  },
  {
    id: "w-4",
    name: "Black Motorcycle Jacket",
    category: "Outerwear",
    color: "Black",
    season: ["Spring", "Autumn"],
    brand: "Saint Laurent",
    occasion: ["Casual"],
    material: "Leather",
    isFavorite: true,
    wearCount: 25,
    lastWorn: "2023-09-28",
    dateAdded: "2021-08-20",
    imageUrl: "/images/wardrobe/leather-jacket.png",
    notes: "Condition leather every 6 months.",
  },
  {
    id: "w-5",
    name: "Minimalist White Sneakers",
    category: "Shoes",
    color: "White",
    season: ["Spring", "Summer", "Autumn"],
    brand: "Common Projects",
    occasion: ["Casual", "Smart Casual"],
    material: "Leather",
    isFavorite: true,
    wearCount: 56,
    lastWorn: "2023-10-02",
    dateAdded: "2022-03-10",
    imageUrl: "/images/wardrobe/sneakers.png",
    notes: "Keep clean with a damp cloth.",
  },
  {
    id: "w-6",
    name: "Navy Tailored Blazer",
    category: "Outerwear",
    color: "Navy",
    season: ["Spring", "Autumn", "Winter"],
    brand: "SuitSupply",
    occasion: ["Smart Casual", "Formal"],
    material: "Wool",
    isFavorite: false,
    wearCount: 12,
    lastWorn: "2023-08-15",
    dateAdded: "2021-10-10",
    imageUrl: "/images/wardrobe/blazer.png",
    notes: "Versatile unstructured fit.",
  },
  {
    id: "w-7",
    name: "Charcoal Wool Trousers",
    category: "Bottoms",
    color: "Grey",
    season: ["Autumn", "Winter"],
    brand: "Theory",
    occasion: ["Smart Casual", "Formal"],
    material: "Wool",
    isFavorite: false,
    wearCount: 18,
    lastWorn: "2023-09-20",
    dateAdded: "2022-09-01",
    imageUrl: "/images/wardrobe/jeans.png", // Reusing image
    notes: "Pair with lighter tops for contrast.",
  },
  {
    id: "w-8",
    name: "Olive Green Overshirt",
    category: "Outerwear",
    color: "Olive",
    season: ["Spring", "Autumn"],
    brand: "Folk",
    occasion: ["Casual"],
    material: "Cotton",
    isFavorite: true,
    wearCount: 22,
    lastWorn: "2023-10-01",
    dateAdded: "2023-02-15",
    imageUrl: "/images/wardrobe/white-shirt.png", // Reusing image
    notes: "Good for layering over tees.",
  },
  {
    id: "w-9",
    name: "Black Chelsea Boots",
    category: "Shoes",
    color: "Black",
    season: ["Autumn", "Winter"],
    brand: "R.M. Williams",
    occasion: ["Smart Casual", "Formal"],
    material: "Leather",
    isFavorite: true,
    wearCount: 30,
    lastWorn: "2023-04-10",
    dateAdded: "2021-11-20",
    imageUrl: "/images/wardrobe/sneakers.png", // Reusing image
    notes: "Very comfortable, fits slightly large.",
  },
  {
    id: "w-10",
    name: "Grey Melange T-Shirt",
    category: "Tops",
    color: "Grey",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    brand: "Sunspel",
    occasion: ["Casual", "Lounge"],
    material: "Cotton",
    isFavorite: false,
    wearCount: 45,
    lastWorn: "2023-10-06",
    dateAdded: "2022-05-10",
    imageUrl: "/images/wardrobe/white-shirt.png", // Reusing image
    notes: "Staple basic.",
  }
];
